import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  mainSidebar: [
    {
      type: 'category',
      label: '🏁 Tutoriales',
      link: { type: 'generated-index', description: 'Guías paso a paso para usuarios nuevos.' },
      items: [{ type: 'autogenerated', dirName: '01-tutorials' }],
    },
    {
      type: 'category',
      label: '🛠️ Guías de Usuario',
      link: { type: 'generated-index', description: 'Recetas para tareas específicas de configuración y uso.' },
      items: [{ type: 'autogenerated', dirName: '02-how-to' }],
    },
    {
      type: 'category',
      label: '🧠 Conceptos e Innovación',
      collapsed: false,
      link: { type: 'generated-index', description: 'La teoría y decisiones de diseño detrás de Killari.' },
      items: [{ type: 'autogenerated', dirName: '03-explanation' }],
    },
    {
      type: 'category',
      label: '📚 Referencia Técnica',
      link: { type: 'generated-index', description: 'Documentación detallada del código y arquitectura 1:1.' },
      items: [
        {
          type: 'category',
          label: 'Cliente (Electron)',
          items: [{ type: 'autogenerated', dirName: '04-reference/client' }],
        },
        {
          type: 'category',
          label: 'API Engine',
          items: [{ type: 'autogenerated', dirName: '04-reference/api' }],
        },
      ],
    },
  ],
};

export default sidebars;
