import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  mainSidebar: [
    // 1. EXPLANATION: La visión estratégica (Antes era Project Innovation)
    {
      type: "category",
      label: "🚀 Innovación y Conceptos",
      collapsed: false,
      link: {
        type: "generated-index",
        title: "Innovación en Killari",
        description: "Fundamentos teóricos, arquitectura global y el uso de IA en el ecosistema legal.",
      },
      items: [{ type: "autogenerated", dirName: "explanation" }],
    },

    // 2. TUTORIALS: Guías de aprendizaje
    {
      type: "category",
      label: "🏁 Tutoriales",
      items: [{ type: "autogenerated", dirName: "tutorials" }],
    },

    // 3. HOW-TO-GUIDES: Guías de resolución de tareas
    {
      type: "category",
      label: "🛠️ Guías Prácticas",
      items: [{ type: 'autogenerated', dirName: 'how-to-guides' }],
    },

    // 4. REFERENCE: La documentación técnica 1:1 (Antes era Code Reference)
    {
      type: "category",
      label: "📚 Referencia Técnica",
      collapsed: true,
      link: {
        type: "generated-index",
        title: "Referencia del Código",
        description: "Documentación técnica de los procesos de la API y el Cliente de Escritorio.",
      },
      items: [
        {
          type: "category",
          label: "API Engine",
          items: [{ type: "autogenerated", dirName: "reference/api" }],
        },
        {
          type: "category",
          label: "Cliente (Electron)",
          items: [{ type: "autogenerated", dirName: "reference/client" }],
        },
      ],
    },
  ],
};

export default sidebars;
