import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Sidebar principal de la documentación
  mainSidebar: [
    // 1. ENFOQUE WINNER: Estratégico y de Negocio
    {
      type: 'category',
      label: '🚀 Project Innovation',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '01-project-innovation',
        },
      ],
    },
    // 2. ENFOQUE ESPEJO 1-1: Referencia Técnica Detallada
    {
      type: 'category',
      label: '💻 Code Reference (1:1)',
      collapsed: true,
      link: {
        type: 'generated-index',
        title: 'Technical Documentation',
        description:
          'Exploración detallada de la arquitectura de Killari, desde el núcleo de Electron hasta la integración de APIs.',
      },
      items: [
        {
          type: 'category',
          label: 'Backend & API',
          items: [{ type: 'autogenerated', dirName: '02-code-reference/api' }],
        },
        {
          type: 'category',
          label: 'Client (Electron)',
          items: [{ type: 'autogenerated', dirName: '02-code-reference/client' }],
        },
      ],
    },
  ],
};

export default sidebars;
